language: php
php:
  - 5.6
  - 7.0
  - 7.1
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
sudo: false
before_script:
  - composer self-update
  - composer install
  - touch .env
script:
 - ./vendor/bin/phpunit
